apiVersion: batch/v1
kind: Job
metadata:
  generateName: schema-migrate-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
     - name: presyncjob
       image: busybox                 
       command: ["echo", "job-presync"]   
