apiVersion: batch/v1
kind: Job
metadata:
  generateName: jobpresync-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    metadata:
      name: job
    spec:
      containers:
      - name: presyncjob
        image: busybox                 
        command: ["echo", "L application sera synchronisé avec un nouvel état désiré"]   
      restartPolicy: Never
